[package]
name = "value_listener"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
